# Generated by Django 5.1.7 on 2025-03-13 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glovo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ky',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='combo',
            name='combo_name_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='combo',
            name='combo_name_ky',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='combo',
            name='combo_name_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='combo',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='combo',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='combo',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='store_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='glovo_app.store'),
        ),
        migrations.AddField(
            model_name='contact',
            name='store_ky',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='glovo_app.store'),
        ),
        migrations.AddField(
            model_name='contact',
            name='store_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='glovo_app.store'),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ky',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='glovo_app.category'),
        ),
        migrations.AddField(
            model_name='store',
            name='category_ky',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='glovo_app.category'),
        ),
        migrations.AddField(
            model_name='store',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='glovo_app.category'),
        ),
        migrations.AddField(
            model_name='store',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_name_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
