# Generated by Django 5.1.7 on 2025-03-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glovo_app', '0002_category_category_name_en_category_category_name_ky_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='store_en',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='store_ky',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='store_ru',
        ),
        migrations.RemoveField(
            model_name='store',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='store',
            name='category_ky',
        ),
        migrations.RemoveField(
            model_name='store',
            name='category_ru',
        ),
        migrations.AddField(
            model_name='store',
            name='address_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='address_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='address_ru',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
