# Generated by Django 5.1.7 on 2025-03-15 05:56

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glovo_app', '0003_remove_contact_store_en_remove_contact_store_ky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='glovo_app.store'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='contact',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='glovo_app.store'),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='glovo_app.store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_list', to='glovo_app.category'),
        ),
        migrations.AlterField(
            model_name='storereview',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_store', to=settings.AUTH_USER_MODEL),
        ),
    ]
